{
 "title": "WMI Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HDD Disk Free (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes",
     "legendFormat": "{{volume}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Request queue ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "windows_logical_disk_requests_queued",
     "legendFormat": "{{volume}}/{{instance}}"
    }
   ]
  },
  { "title": "Users and Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "windows_os_users", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "windows_os_processes", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Physical memory free (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "windows_os_physical_memory_free_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Virtual memory free (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "windows_os_virtual_memory_free_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}